***form excel file to mysql table with jupyter notebook***

In [16]:
# pip install xlrd

In [1]:
import xlrd

In [2]:
workbook = xlrd.open_workbook('ListEleve_20231115.xls')

In [3]:
worksheet = workbook.sheet_by_name('Sheet1') #by name

In [4]:
worksheet = workbook.sheet_by_index(0)  #by index

In [5]:
import datetime as dt

In [6]:
# for ind in range(0,6):
#     worksheet = workbook.sheet_by_index(ind)  #by index
#     for i in range(14,worksheet.nrows):
#         for j in [2,5,11,12,16,23,26,30]:
#             if i>14 and j==5:
#                 serial = worksheet.cell(i, j).value
#                 seconds = (serial - 25569) * 86400.0
#                 print("( "+str(i)+", "+str(j)+ ") ====>  "+dt.date.fromtimestamp(seconds).strftime('%d/%m/%Y') )
                
#             elif i>14 and j==26 :
#                 print("( "+str(i)+", "+str(j)+ ") ====>  ", int(worksheet.cell(i, j).value) )
#             else:
#                 print("( "+str(i)+", "+str(j)+ ") ====>  "+ str(worksheet.cell(i, j).value) )

***install mySQL Connecteur***

In [7]:
# Setup MySQL for us to send data and create a new DB
import mysql.connector as mysql
from mysql.connector import MySQLConnection # using Class for function call
import pandas as pd # create dataframe

# from python_to_myql_config import read_db_config #calling config file, (you need to )
# sotred user credentials I have, or use the block of code velow 

import csv

In [8]:
nb_rows=0
for ind in range(0,6):
    worksheet = workbook.sheet_by_index(ind)  #by index
    for i in range(15,worksheet.nrows):
        birth = dt.date.fromtimestamp((worksheet.cell(i, 5).value - 25569) * 86400.0).strftime('%Y/%m/%d')
        num=int(worksheet.cell(i, 26).value)
        uni = worksheet.cell(i, 23).value
        prenom =worksheet.cell(i, 12).value
        nom = worksheet.cell(i, 16).value
        genre = worksheet.cell(i, 11).value
        born_pl = worksheet.cell(i, 2).value
        classe = worksheet.cell(i, 30).value
        # test of connection
        cnx = mysql.connect(user='root', password = '', host ='127.0.0.1',database='mz2023')
        #Creating a cursor object using the cursor() method
        cursor = cnx.cursor()

        # Preparing SQL query to INSERT a record into the database.
        insert_stmt = (
           "INSERT INTO etudiants(num_classe , code , prenom , nom , sexe , dt_naissance , lieu_naissance ,classe)"
            " VALUES (%s, %s, %s, %s, %s, %s, %s, %s)"
        )
        data = (num, uni , prenom , nom , genre , birth  , born_pl , classe )
        try:
         # Executing the SQL command
            cursor.execute(insert_stmt, data)
        # Commit your changes in the database
            cnx.commit()
            nb_rows+=1
            cnx.close()
        except:
           # Rolling back in case of error
            cnx.rollback()
            print("Not completed successfully")
print(nb_rows)
        #Closing the connection

182

In [9]:
ind=3
worksheet = workbook.sheet_by_index(ind)  #by index
for i in range(15,worksheet.nrows):
    for j in [2,5,11,12,16,23,26,30]:
        if  j==5:
            serial = worksheet.cell(i, j).value
            seconds = (serial - 25569) * 86400.0
            print("( "+str(i)+", "+str(j)+ ") ====>  "+dt.date.fromtimestamp(seconds).strftime('%d/%m/%Y') )

        elif  j==26 :
            print("( "+str(i)+", "+str(j)+ ") ====>  ", int(worksheet.cell(i, j).value) )
        else:
            print("( "+str(i)+", "+str(j)+ ") ====>  "+ str(worksheet.cell(i, j).value) )

( 15, 2) ====>  فاس
( 15, 5) ====>  26/05/2010
( 15, 11) ====>  أنثى
( 15, 12) ====>  مروة
( 15, 16) ====>  رقاس
( 15, 23) ====>  C160016844
( 15, 26) ====>   1
( 15, 30) ====>  2ASCG-2
( 16, 2) ====>  ادرج
( 16, 5) ====>  05/10/2010
( 16, 11) ====>  أنثى
( 16, 12) ====>  اية
( 16, 16) ====>  شاكير
( 16, 23) ====>  C160018203
( 16, 26) ====>   2
( 16, 30) ====>  2ASCG-2
( 17, 2) ====>  تافجيغت
( 17, 5) ====>  05/07/2010
( 17, 11) ====>  ذكر
( 17, 12) ====>  وسيم
( 17, 16) ====>  أيوجيل
( 17, 23) ====>  C160083526
( 17, 26) ====>   3
( 17, 30) ====>  2ASCG-2
( 18, 2) ====>  تافجيغت
( 18, 5) ====>  07/03/2011
( 18, 11) ====>  أنثى
( 18, 12) ====>  هبة
( 18, 16) ====>  مزر
( 18, 23) ====>  C160083528
( 18, 26) ====>   4
( 18, 30) ====>  2ASCG-2
( 19, 2) ====>  فاس
( 19, 5) ====>  07/09/2010
( 19, 11) ====>  ذكر
( 19, 12) ====>  محسن
( 19, 16) ====>  باعوش
( 19, 23) ====>  C161030164
( 19, 26) ====>   5
( 19, 30) ====>  2ASCG-2
( 20, 2) ====>  فاس
( 20, 5) ====>  02/09/2010
( 20, 11) ====>  أنثى
( 20, 12) ====>  ايمان
( 20, 16) ====>  سخسوخ
( 20, 23) ====>  C163056326
( 20, 26) ====>   6
( 20, 30) ====>  2ASCG-2
( 21, 2) ====>  فاس
( 21, 5) ====>  22/01/2011
( 21, 11) ====>  ذكر
( 21, 12) ====>  أيوب
( 21, 16) ====>  يخلف
( 21, 23) ====>  C163083518
( 21, 26) ====>   7
( 21, 30) ====>  2ASCG-2
( 22, 2) ====>  فاس
( 22, 5) ====>  22/10/2010
( 22, 11) ====>  ذكر
( 22, 12) ====>  اسامة
( 22, 16) ====>  ابرشان
( 22, 23) ====>  C165082927
( 22, 26) ====>   8
( 22, 30) ====>  2ASCG-2
( 23, 2) ====>  المركزالصحي أدرج
( 23, 5) ====>  15/03/2011
( 23, 11) ====>  أنثى
( 23, 12) ====>  فردوس
( 23, 16) ====>  اعنن
( 23, 23) ====>  C165083541
( 23, 26) ====>   9
( 23, 30) ====>  2ASCG-2
( 24, 2) ====>  تافجيغت
( 24, 5) ====>  09/09/2010
( 24, 11) ====>  أنثى
( 24, 12) ====>  جمعة
( 24, 16) ====>  بعوش
( 24, 23) ====>  C167082928
( 24, 26) ====>   10
( 24, 30) ====>  2ASCG-2
( 25, 2) ====>  فاس
( 25, 5) ====>  25/02/2010
( 25, 11) ====>  ذكر
( 25, 12) ====>  حمزة
( 25, 16) ====>  بوجو
( 25, 23) ====>  C167082929
( 25, 26) ====>   11
( 25, 30) ====>  2ASCG-2
( 26, 2) ====>  تافجيغت
( 26, 5) ====>  05/08/2010
( 26, 11) ====>  ذكر
( 26, 12) ====>  إلياس
( 26, 16) ====>  شداق
( 26, 23) ====>  C168083507
( 26, 26) ====>   12
( 26, 30) ====>  2ASCG-2
( 27, 2) ====>  صفرو
( 27, 5) ====>  23/02/2010
( 27, 11) ====>  أنثى
( 27, 12) ====>  منال
( 27, 16) ====>  المرابح
( 27, 23) ====>  C169082932
( 27, 26) ====>   13
( 27, 30) ====>  2ASCG-2
( 28, 2) ====>  تافجيغت
( 28, 5) ====>  09/10/2010
( 28, 11) ====>  ذكر
( 28, 12) ====>  نزيه
( 28, 16) ====>  أقشبور
( 28, 23) ====>  C169083520
( 28, 26) ====>   14
( 28, 30) ====>  2ASCG-2
( 29, 2) ====>  قنيطرة
( 29, 5) ====>  18/12/2009
( 29, 11) ====>  أنثى
( 29, 12) ====>  ريهام
( 29, 16) ====>  سالمي
( 29, 23) ====>  F164071672
( 29, 26) ====>   15
( 29, 30) ====>  2ASCG-2
( 30, 2) ====>  تافجيغت
( 30, 5) ====>  01/09/2007
( 30, 11) ====>  ذكر
( 30, 12) ====>  سمير
( 30, 16) ====>  جرتال
( 30, 23) ====>  N130291684
( 30, 26) ====>   16
( 30, 30) ====>  2ASCG-2
( 31, 2) ====>  صفرو
( 31, 5) ====>  19/02/2008
( 31, 11) ====>  ذكر
( 31, 12) ====>  عثمان
( 31, 16) ====>  البرج
( 31, 23) ====>  N134291694
( 31, 26) ====>   17
( 31, 30) ====>  2ASCG-2
( 32, 2) ====>  دوار ايت لحسن
( 32, 5) ====>  28/12/2007
( 32, 11) ====>  أنثى
( 32, 12) ====>  فدوى
( 32, 16) ====>  امعلاوي
( 32, 23) ====>  N134291745
( 32, 26) ====>   18
( 32, 30) ====>  2ASCG-2
( 33, 2) ====>  تافجيغت
( 33, 5) ====>  13/05/2007
( 33, 11) ====>  ذكر
( 33, 12) ====>  ياسين
( 33, 16) ====>  هبيلة
( 33, 23) ====>  N135090257
( 33, 26) ====>   19
( 33, 30) ====>  2ASCG-2
( 34, 2) ====>  تافجيغت
( 34, 5) ====>  18/03/2008
( 34, 11) ====>  ذكر
( 34, 12) ====>  محمد امين
( 34, 16) ====>  جاري
( 34, 23) ====>  N138291690
( 34, 26) ====>   20
( 34, 30) ====>  2ASCG-2
( 35, 2) ====>  م ص أدرج
( 35, 5) ====>  07/08/2009
( 35, 11) ====>  ذكر
( 35, 12) ====>  معاد
( 35, 16) ====>  بنهري
( 35, 23) ====>  N158031061
( 35, 26) ====>   21
( 35, 30) ====>  2ASCG-2
( 36, 2) ====>  تافجيغت
( 36, 5) ====>  02/04/2010
( 36, 11) ====>  ذكر
( 36, 12) ====>  مراد
( 36, 16) ====>  أيوجيل
( 36, 23) ====>  C160083527
( 36, 26) ====>   22
( 36, 30) ====>  2ASCG-2
( 37, 2) ====>
( 37, 5) ====>  24/08/2010
( 37, 11) ====>  ذكر
( 37, 12) ====>  لحسن
( 37, 16) ====>  جلال
( 37, 23) ====>  C163083538
( 37, 26) ====>   23
( 37, 30) ====>  2ASCG-2
( 38, 2) ====>  ايت لحسن تافجيغت
( 38, 5) ====>  23/04/2010
( 38, 11) ====>  ذكر
( 38, 12) ====>  نبيل
( 38, 16) ====>  بعوش
( 38, 23) ====>  C164082924
( 38, 26) ====>   24
( 38, 30) ====>  2ASCG-2
( 39, 2) ====>  صفرو
( 39, 5) ====>  26/01/2011
( 39, 11) ====>  ذكر
( 39, 12) ====>  ادم
( 39, 16) ====>  الحجوي
( 39, 23) ====>  C169083519
( 39, 26) ====>   25
( 39, 30) ====>  2ASCG-2
( 40, 2) ====>  جماعة تافجيغت
( 40, 5) ====>  20/10/2008
( 40, 11) ====>  ذكر
( 40, 12) ====>  جواد
( 40, 16) ====>  جرتال
( 40, 23) ====>  N148103653
( 40, 26) ====>   26
( 40, 30) ====>  2ASCG-2
( 41, 2) ====>  فاس
( 41, 5) ====>  07/11/2009
( 41, 11) ====>  ذكر
( 41, 12) ====>  يوسف
( 41, 16) ====>  مزر
( 41, 23) ====>  N153031047
( 41, 26) ====>   27
( 41, 30) ====>  2ASCG-2
( 42, 2) ====>  تافجيغت
( 42, 5) ====>  25/05/2009
( 42, 11) ====>  ذكر
( 42, 12) ====>  عماد
( 42, 16) ====>  التامستي
( 42, 23) ====>  N156031167
( 42, 26) ====>   28
( 42, 30) ====>  2ASCG-2